const DB_NAME='GamayatiDB',DB_VERSION=5;
let db,clients=[],products=[],inventory=[],invoices=[],settings={monthEndDay:25};
const $=id=>document.getElementById(id);
const now=()=>new Date().toISOString();
const monthKey=(d=new Date())=>d.toISOString().slice(0,7);
const money=n=>Number(n||0).toFixed(2);
const num=n=>Number(n||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const dateTime=iso=>iso?new Date(iso).toLocaleString('ar-EG',{dateStyle:'short',timeStyle:'short'}):'—';
const dateOnly=iso=>iso?new Date(iso).toLocaleDateString('ar-EG'):'—';
const monthLabel=m=>{if(!m)return'—';const [y,mo]=String(m).split('-');return `${mo}/${y}`};
function toast(msg){const el=$('toast');if(!el)return;el.textContent=msg;el.style.display='block';clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>el.style.display='none',2400)}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=e=>{const d=e.target.result;[
['clients',{keyPath:'id',autoIncrement:true}],['products',{keyPath:'id',autoIncrement:true}],
['inventory',{keyPath:'productId'}],['invoices',{keyPath:'id',autoIncrement:true}],
['invoiceItems',{keyPath:'id',autoIncrement:true}],['inventoryTransactions',{keyPath:'id',autoIncrement:true}],
['auditLogs',{keyPath:'id',autoIncrement:true}],['settings',{keyPath:'key'}]
].forEach(([n,o])=>{if(!d.objectStoreNames.contains(n))d.createObjectStore(n,o)})};
r.onsuccess=()=>{db=r.result;db.onversionchange=()=>db.close();resolve()};r.onerror=()=>reject(r.error)})}
function all(store){return new Promise((res,rej)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function req(store,method,arg,tx){return new Promise((res,rej)=>{const r=tx.objectStore(store)[method](arg);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function add(store,arg){return new Promise((res,rej)=>{const tx=db.transaction(store,'readwrite');const r=tx.objectStore(store).add(arg);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function put(store,arg){return new Promise((res,rej)=>{const tx=db.transaction(store,'readwrite');const r=tx.objectStore(store).put(arg);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function read(store,key){return new Promise((res,rej)=>{const r=db.transaction(store).objectStore(store).get(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function waitTx(tx){return new Promise((res,rej)=>{tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error||new Error('transaction error'));tx.onabort=()=>rej(tx.error||new Error('transaction aborted'))})}
function activeClients(){return clients.filter(x=>!x.archived)}
function activeProducts(){return products.filter(x=>!x.archived)}
function seqCode(prefix,list,field){let max=0;for(const x of list){const m=String(x?.[field]||'').match(new RegExp('^'+prefix+'-(\\d+)$','i'));if(m)max=Math.max(max,Number(m[1]))}return `${prefix}-${String(max+1).padStart(6,'0')}`}
async function refresh(){
 clients=await all('clients');products=await all('products');inventory=await all('inventory');invoices=await all('invoices');
 const s=await read('settings','monthEndDay');settings.monthEndDay=Number(s?.value||25);$('monthEndDay').value=settings.monthEndDay;
 renderDashboard();renderClients();renderProducts();renderInventory();renderClientSelect();renderInvoices();renderLines();renderInventoryLog();
}
function currentStatus(c){
 const m=monthKey(),done=invoices.some(i=>i.clientId===c.id&&i.serviceMonth===m&&i.status==='CONFIRMED'&&!i.reversed);
 if(done)return['green','✓ تم الصرف'];
 return[new Date().getDate()>settings.monthEndDay?'red':'yellow',new Date().getDate()>settings.monthEndDay?'* متأخر':'! لم يصرف'];
}
function latestDispense(c){
 return invoices.filter(i=>i.clientId===c.id&&i.status==='CONFIRMED').sort((a,b)=>String(b.issuedAt||'').localeCompare(String(a.issuedAt||'')))[0];
}
function renderDashboard(){
 $('statClients').textContent=activeClients().length;$('statProducts').textContent=activeProducts().length;
 const m=monthKey(),ids=new Set(invoices.filter(i=>i.serviceMonth===m&&i.status==='CONFIRMED'&&!i.reversed).map(i=>i.clientId));
 $('statDispensed').textContent=ids.size;$('statStock').textContent=money(inventory.reduce((s,x)=>s+num(x.quantity),0));
 const moves=inventoryTransactionsCache().slice(0,5);
 $('monthlyStatus').innerHTML=activeClients().map(c=>{const[cl,tx]=currentStatus(c),last=latestDispense(c);return `<div class="item"><div class="info"><b>${esc(c.fullName)}</b><div class="muted">بطاقة: ${esc(c.cardNumber)} | السري: ${esc(c.secretCode||'—')}</div><div class="muted">آخر صرف: ${last?`${monthLabel(last.serviceMonth)} — ${dateTime(last.issuedAt)}`:'لا يوجد'}</div></div><span class="status ${cl}">${tx}</span></div>`}).join('')||'<div class="muted">لا يوجد عملاء.</div>';
 const recent=$('recentInventoryMoves');if(recent)recent.innerHTML=moves.map(renderMoveCompact).join('')||'<div class="muted">لا توجد حركات مخزون حتى الآن.</div>';
}
let inventoryTxCache=[];
function inventoryTransactionsCache(){return inventoryTxCache}
function typeLabel(t){return t==='RECEIPT'?'استلام':t==='SALE'?'صرف':t==='REVERSAL'?'عكس صرف':'تعديل رصيد'}
function typeClass(t){return t==='RECEIPT'?'green':t==='SALE'?'red':t==='REVERSAL'?'yellow':'blue'}
function productName(id){return products.find(p=>p.id===id)?.name||`صنف #${id}`}
function renderMoveCompact(x){return `<div class="movement compact"><div><b>${esc(productName(x.productId))}</b><div class="muted">${typeLabel(x.type)} • ${dateTime(x.createdAt)}</div></div><div class="movement-qty ${typeClass(x.type)}">${x.quantityChange>0?'+':''}${money(x.quantityChange)}</div></div>`}
function renderClients(){
 const q=($('clientSearch').value||'').trim().toLowerCase();
 const list=activeClients().filter(c=>[c.fullName,c.cardNumber,c.phone,c.secretCode].join(' ').toLowerCase().includes(q));
 $('clientsList').innerHTML=list.map(c=>{const[cl,tx]=currentStatus(c),last=latestDispense(c);return `<div class="item client-item"><div class="info"><div class="row-title"><b>${esc(c.fullName)}</b><span class="status ${cl}">${tx}</span></div><div class="muted">البطاقة: ${esc(c.cardNumber)} | الرقم السري: <b>${esc(c.secretCode||'—')}</b></div><div class="muted">التموين: ${num(c.rationCount)} | الخبز: ${num(c.flourCount)}${c.phone?` | الهاتف: ${esc(c.phone)}`:''}</div><div class="muted">آخر صرف: ${last?`${monthLabel(last.serviceMonth)} — ${dateTime(last.issuedAt)}`:'لا يوجد'}</div>${c.address?`<div class="muted">العنوان: ${esc(c.address)}</div>`:''}${c.notes?`<div class="note-line">ملاحظة: ${esc(c.notes)}</div>`:''}</div><div class="actions"><button class="secondary" onclick="openClientHistory(${c.id})">📅 الشهور</button><button class="secondary" onclick="editClient(${c.id})">تعديل</button><button class="danger" onclick="archiveClient(${c.id})">أرشفة</button></div></div>`}).join('')||'<div class="panel">لا يوجد عملاء.</div>';
}
function renderProducts(){
 const q=($('productSearch').value||'').trim().toLowerCase();
 const list=activeProducts().filter(p=>[p.name,p.code,p.unit].join(' ').toLowerCase().includes(q));
 $('productsList').innerHTML=list.map(p=>{const st=inventory.find(x=>x.productId===p.id),qty=num(st?.quantity),low=qty<=num(p.minimumStock);return `<div class="item product-item"><div class="info"><div class="row-title"><b>${esc(p.name)}</b><span class="code">${esc(p.code||'—')}</span></div><div class="muted">الوحدة: ${esc(p.unit)} | السعر: ${money(p.price)} جنيه</div><div class="stock-line">المخزون: <b class="${low?'low':''}">${money(qty)}</b>${low?'<span class="status red">تحت الحد الأدنى</span>':''}</div></div><div class="actions"><button class="primary" onclick="openReceiveStock(${p.id})">＋ استلام</button><button class="secondary" onclick="editProduct(${p.id})">تعديل</button><button class="danger" onclick="archiveProduct(${p.id})">أرشفة</button></div></div>`}).join('')||'<div class="panel">لا توجد أصناف.</div>';
}
function renderInventory(){
 const q=($('inventorySearch')?.value||'').trim().toLowerCase();
 const list=activeProducts().filter(p=>[p.name,p.code].join(' ').toLowerCase().includes(q));
 $('inventoryCards').innerHTML=list.map(p=>{const st=inventory.find(x=>x.productId===p.id),qty=num(st?.quantity),low=qty<=num(p.minimumStock);return `<div class="card stock-card"><div class="row-title"><h3>${esc(p.name)}</h3><span class="code">${esc(p.code||'—')}</span></div><div class="stock-big ${low?'low':''}">${money(qty)}</div><div class="muted">${esc(p.unit)} • حد أدنى ${money(p.minimumStock)}</div><button class="primary full" onclick="openReceiveStock(${p.id})">استلام مخزون</button></div>`}).join('')||'<div class="panel">لا توجد أصناف.</div>';
}
function renderInventoryLog(){
 const q=($('movementSearch')?.value||'').trim().toLowerCase();const type=$('movementType')?.value||'';const from=$('movementFrom')?.value||'';const to=$('movementTo')?.value||'';
 let list=inventoryTxCache.filter(x=>{const pn=productName(x.productId).toLowerCase(),note=String(x.note||'').toLowerCase();if(q&&!`${pn} ${note} ${x.referenceId||''}`.includes(q))return false;if(type&&x.type!==type)return false;const d=x.createdAt?new Date(x.createdAt):null;if(from&&d&&d<new Date(from+'T00:00:00'))return false;if(to&&d&&d>new Date(to+'T23:59:59.999'))return false;return true});
 $('inventoryLog').innerHTML=list.map(x=>{const change=num(x.quantityChange);return `<div class="movement"><div class="info"><div class="row-title"><b>${esc(productName(x.productId))}</b><span class="status ${typeClass(x.type)}">${typeLabel(x.type)}</span></div><div class="muted">التاريخ: ${dateTime(x.createdAt)}${x.referenceId?` | مرجع: #${esc(x.referenceId)}`:''}</div><div class="muted">قبل: ${money(x.quantityBefore)} → بعد: ${money(x.quantityAfter)}</div>${x.note?`<div class="note-line"><b>الملاحظة:</b> ${esc(x.note)}</div>`:''}</div><b class="movement-qty ${typeClass(x.type)}">${change>0?'+':''}${money(change)}</b></div>`}).join('')||'<div class="panel">لا توجد حركات مطابقة.</div>';
}
function renderClientSelect(){$('dispClient').innerHTML='<option value="">اختر العميل</option>'+activeClients().map(c=>`<option value="${c.id}">${esc(c.fullName)} — ${esc(c.cardNumber)}</option>`).join('')}
function renderLines(){if(!$('dispenseLines').querySelector('.line'))addLine()}
function addLine(){const box=$('dispenseLines'),row=document.createElement('div');row.className='line';row.innerHTML=`<select onchange="calcTotal()"><option value="">اختر الصنف</option>${activeProducts().map(p=>`<option value="${p.id}">${esc(p.name)} (${money(p.price)})</option>`).join('')}</select><input type="number" min="0.01" step="0.01" value="1" oninput="calcTotal()"><span class="lineTotal">0.00</span><button type="button" class="danger" onclick="this.parentElement.remove();calcTotal()">×</button>`;box.appendChild(row);calcTotal()}
function calcTotal(){let t=0;document.querySelectorAll('#dispenseLines .line').forEach(r=>{const p=products.find(x=>x.id==r.querySelector('select').value),q=num(r.querySelector('input').value),v=p?q*p.price:0;r.querySelector('.lineTotal').textContent=money(v);t+=v});$('dispTotal').textContent=money(t)}
$('dispClient').addEventListener('change',()=>{const c=clients.find(x=>x.id===Number($('dispClient').value));$('dispClientInfo').textContent=c?`بطاقة ${c.cardNumber} — الرقم السري ${c.secretCode||'—'} — أفراد التموين ${num(c.rationCount)} — أفراد الخبز ${num(c.flourCount)}`:''});
async function confirmDispense(){
 const clientId=Number($('dispClient').value);if(!clientId)return alert('اختر العميل أولًا');const c=clients.find(x=>x.id===clientId),m=monthKey();
 if(invoices.some(i=>i.clientId===clientId&&i.serviceMonth===m&&i.status==='CONFIRMED'&&!i.reversed))return alert('هذا العميل لديه صرف مؤكد بالفعل هذا الشهر.');
 const lines=[...document.querySelectorAll('#dispenseLines .line')].map(r=>({productId:Number(r.querySelector('select').value),quantity:num(r.querySelector('input').value)})).filter(x=>x.productId&&x.quantity>0);
 if(!lines.length)return alert('أضف صنفًا واحدًا على الأقل');const seen=new Set();for(const l of lines){if(seen.has(l.productId))return alert('لا تكرر نفس الصنف.');seen.add(l.productId)}
 const prepared=[];for(const l of lines){const p=products.find(x=>x.id===l.productId),st=inventory.find(x=>x.productId===l.productId);if(!p||!st||num(st.quantity)<l.quantity)return alert(`المخزون غير كافٍ للصنف: ${p?.name||''}`);prepared.push({productId:p.id,productNameSnapshot:p.name,quantity:l.quantity,unitPrice:p.price,lineTotal:l.quantity*p.price})}
 const total=prepared.reduce((s,x)=>s+x.lineTotal,0);if(!confirm(`تأكيد الصرف النهائي؟\nالإجمالي: ${money(total)} جنيه\nلا يمكن حذف الفاتورة بعد التأكيد.\nالتصحيح يتم بحركة عكس تحفظ الفاتورة الأصلية.`))return;
 const tx=db.transaction(['invoices','invoiceItems','inventory','inventoryTransactions','auditLogs'],'readwrite');
 try{
  const invoiceId=await req('invoices','add',{clientId,clientNameSnapshot:c.fullName,cardNumberSnapshot:c.cardNumber,serviceMonth:m,issuedAt:now(),status:'CONFIRMED',reversed:false,total},tx);
  for(const x of prepared){await req('invoiceItems','add',{invoiceId,...x},tx);const st=inventory.find(y=>y.productId===x.productId),before=num(st.quantity),after=before-x.quantity;st.quantity=after;st.updatedAt=now();await req('inventory','put',st,tx);await req('inventoryTransactions','add',{productId:x.productId,type:'SALE',quantityChange:-x.quantity,quantityBefore:before,quantityAfter:after,referenceId:invoiceId,note:`فاتورة #${invoiceId}`,createdAt:now()},tx)}
  await req('auditLogs','add',{action:'CREATE_DISPENSE',entityType:'invoice',entityId:invoiceId,createdAt:now()},tx);await waitTx(tx);
  alert(`تم الحفظ بنجاح\nالفاتورة #${invoiceId}\nالإجمالي: ${money(total)} جنيه`);$('dispClient').value='';$('dispenseLines').innerHTML='';await refresh()
 }catch(e){console.error(e);alert('لم يتم حفظ العملية. لم يتم خصم أي مخزون بسبب فشل المعاملة.')}
}
function renderInvoices(){const q=($('invoiceSearch').value||'').toLowerCase();$('invoicesList').innerHTML=invoices.slice().sort((a,b)=>b.id-a.id).filter(i=>String(i.id).includes(q)||String(i.clientNameSnapshot||'').toLowerCase().includes(q)).map(i=>`<div class="item"><div class="info"><b>فاتورة #${i.id}</b><div>${esc(i.clientNameSnapshot)} — ${esc(i.cardNumberSnapshot)}</div><div class="muted">${i.serviceMonth} | ${new Date(i.issuedAt).toLocaleString('ar-EG')} | ${money(i.total)} جنيه</div></div><div class="actions"><button class="secondary" onclick="openInvoice(${i.id})">فتح</button>${!i.reversed?`<button class="danger" onclick="reverseInvoice(${i.id})">عكس العملية</button>`:''}<span class="status ${i.reversed?'red':'green'}">${i.reversed?'ملغاة بعكس حركة':'مؤكدة'}</span></div></div>`).join('')||'<div class="panel">لا توجد فواتير.</div>'}
async function openInvoice(id){const inv=invoices.find(i=>i.id===id);if(!inv)return;const items=(await all('invoiceItems')).filter(x=>x.invoiceId===id);$('invoiceDetailsBody').innerHTML=`<h3>تفاصيل الفاتورة #${inv.id}</h3><p><b>العميل:</b> ${esc(inv.clientNameSnapshot)} — ${esc(inv.cardNumberSnapshot)}</p><p><b>الشهر:</b> ${esc(inv.serviceMonth)} | <b>التاريخ:</b> ${new Date(inv.issuedAt).toLocaleString('ar-EG')}</p><div class="invoice-detail-table"><div class="invoice-detail-row head"><b>الصنف</b><b>الكمية</b><b>السعر</b><b>الإجمالي</b></div>${items.map(x=>`<div class="invoice-detail-row"><span>${esc(x.productNameSnapshot||productName(x.productId))}</span><span>${money(x.quantity)}</span><span>${money(x.unitPrice)}</span><b>${money(x.lineTotal)}</b></div>`).join('')}</div><p class="total">الإجمالي: <b>${money(inv.total)} جنيه</b></p>${inv.reversed?'<div class="warning">هذه الفاتورة تم عكس أثرها على المخزون، مع الاحتفاظ بسجلها الأصلي.</div>':''}`;$('invoiceDetailsDialog').showModal()}

async function reverseInvoice(id){
 const inv=invoices.find(i=>i.id===id);if(!inv||inv.reversed)return;if(!confirm('سيتم إنشاء حركة عكس وإرجاع الكميات للمخزون مع الاحتفاظ بالفاتورة الأصلية. هل تريد المتابعة؟'))return;
 const items=(await all('invoiceItems')).filter(x=>x.invoiceId===id);const tx=db.transaction(['invoices','inventory','inventoryTransactions','auditLogs'],'readwrite');
 try{inv.reversed=true;inv.reversedAt=now();await req('invoices','put',inv,tx);for(const x of items){const st=inventory.find(y=>y.productId===x.productId);if(!st)throw Error('inventory missing');const before=num(st.quantity),after=before+num(x.quantity);st.quantity=after;st.updatedAt=now();await req('inventory','put',st,tx);await req('inventoryTransactions','add',{productId:x.productId,type:'REVERSAL',quantityChange:num(x.quantity),quantityBefore:before,quantityAfter:after,referenceId:id,note:`عكس فاتورة #${id}`,createdAt:now()},tx)}await req('auditLogs','add',{action:'REVERSE_INVOICE',entityType:'invoice',entityId:id,createdAt:now()},tx);await waitTx(tx);await refresh();toast('تم عكس الفاتورة وإرجاع المخزون مع حفظ الأصل.')}catch(e){console.error(e);alert('فشل العكس ولم تُعتمد العملية.')}
}
function monthArabic(m){if(!m)return'—';const [y,mo]=String(m).split('-').map(Number);return new Date(y,mo-1,1).toLocaleDateString('ar-EG',{year:'numeric',month:'long'})}
function clientMonthHistory(c){const months=new Set();const base=new Date();for(let i=0;i<24;i++){const d=new Date(base.getFullYear(),base.getMonth()-i,1);months.add(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`)}invoices.filter(i=>i.clientId===c.id).forEach(i=>months.add(i.serviceMonth));return [...months].filter(Boolean).sort().reverse().map(m=>{const rows=invoices.filter(i=>i.clientId===c.id&&i.serviceMonth===m&&i.status==='CONFIRMED');const active=rows.find(i=>!i.reversed),rev=rows.find(i=>i.reversed);if(active)return{m,status:'تم الصرف',cl:'green',date:new Date(active.issuedAt).toLocaleDateString('ar-EG'),inv:active};if(rev)return{m,status:'عُكست العملية',cl:'yellow',date:new Date(rev.reversedAt||rev.issuedAt).toLocaleDateString('ar-EG'),inv:rev};const late=m===monthKey()&&new Date().getDate()>settings.monthEndDay;return{m,status:m===monthKey()?(late?'متأخر':'لم يصرف'):'لم يصرف',cl:m===monthKey()&&late?'red':'yellow',date:'—',inv:null}})}
function openClientHistory(id){const c=clients.find(x=>x.id===id);if(!c)return;const h=clientMonthHistory(c);$('clientHistoryBody').innerHTML=`<h3>سجل شهور العميل</h3><p><b>${esc(c.fullName)}</b> — بطاقة ${esc(c.cardNumber)}</p>${c.notes?`<div class="note-line"><b>ملاحظات:</b> ${esc(c.notes)}</div>`:''}<div class="month-history">${h.map(x=>`<div class="month-row"><div><b>${monthArabic(x.m)}</b><div class="muted">${x.date}</div></div><span class="status ${x.cl}">${x.status}</span>${x.inv?`<button class="secondary" onclick="document.getElementById('clientHistoryDialog').close();openInvoice(${x.inv.id})">الفاتورة</button>`:''}</div>`).join('')}</div>`;$('clientHistoryDialog').showModal()}
function editClient(id){const c=clients.find(x=>x.id===id);if(!c)return;$('clientId').value=c.id;$('clientName').value=c.fullName;$('cardNumber').value=c.cardNumber;$('secretCode').value=c.secretCode||'';$('rationCount').value=c.rationCount;$('flourCount').value=c.flourCount;$('phone').value=c.phone||'';$('address').value=c.address||'';$('notes').value=c.notes||'';$('clientDialogTitle').textContent='تعديل عميل';$('clientDialog').showModal()}
async function archiveClient(id){if(!confirm('أرشفة العميل؟'))return;try{const c=clients.find(x=>x.id===id);c.archived=true;c.updatedAt=now();await put('clients',c);await refresh();toast('تمت أرشفة العميل')}catch(e){alert('تعذر أرشفة العميل.')}}
function editProduct(id){const p=products.find(x=>x.id===id);if(!p)return;const qty=num(inventory.find(x=>x.productId===id)?.quantity);$('productId').value=p.id;$('productName').value=p.name;$('productCode').value=p.code||'';$('productUnit').value=p.unit||'وحدة';$('productPrice').value=p.price;$('minimumStock').value=p.minimumStock;$('initialStock').value=qty;$('stockChangeNote').value='';$('productDialogTitle').textContent='تعديل صنف';$('productDialog').showModal()}
async function archiveProduct(id){if(!confirm('أرشفة الصنف؟'))return;try{const p=products.find(x=>x.id===id);p.archived=true;p.updatedAt=now();await put('products',p);await refresh();toast('تمت أرشفة الصنف')}catch(e){alert('تعذر أرشفة الصنف.')}}
$('addClientBtn').onclick=()=>{$('clientForm').reset();$('clientId').value='';$('secretCode').value='';$('clientDialogTitle').textContent='إضافة عميل';$('clientDialog').showModal()};
$('addProductBtn').onclick=()=>{$('productForm').reset();$('productId').value='';$('productCode').value='سيُولَّد تلقائيًا';$('initialStock').value=0;$('stockChangeNote').value='';$('productDialogTitle').textContent='إضافة صنف';$('productDialog').showModal()};
$('clientForm').addEventListener('submit',async e=>{e.preventDefault();const id=Number($('clientId').value),old=clients.find(x=>x.id===id),obj={fullName:$('clientName').value.trim(),cardNumber:$('cardNumber').value.trim(),secretCode:$('secretCode').value.trim(),rationCount:num($('rationCount').value),flourCount:num($('flourCount').value),phone:$('phone').value.trim(),address:$('address').value.trim(),notes:$('notes').value.trim(),archived:false,updatedAt:now()};if(!obj.fullName||!obj.cardNumber)return alert('الاسم ورقم البطاقة مطلوبان');if(!obj.secretCode)return alert('الرقم السري مطلوب ويجب إدخاله يدويًا.');try{if(id)await put('clients',{...old,...obj,id});else{obj.createdAt=now();await add('clients',obj)}$('clientDialog').close();await refresh();toast('تم حفظ العميل')}catch(e){console.error(e);alert('حدث خطأ في حفظ العميل: '+(e.message||''))}});
$('productForm').addEventListener('submit',async e=>{e.preventDefault();const id=Number($('productId').value),old=products.find(x=>x.id===id),oldSt=inventory.find(x=>x.productId===id),qty=num($('initialStock').value),oldQty=num(oldSt?.quantity),note=$('stockChangeNote').value.trim();const obj={name:$('productName').value.trim(),code:old?.code||seqCode('P',products,'code'),unit:$('productUnit').value.trim()||'وحدة',price:num($('productPrice').value),minimumStock:num($('minimumStock').value),archived:false,updatedAt:now()};if(!obj.name||obj.price<0||qty<0||obj.minimumStock<0)return alert('بيانات الصنف غير صحيحة');if(id&&qty!==oldQty&&!note)return alert('اكتب ملاحظة عند تغيير الرصيد حتى تُحفظ الحركة في سجل المخزون.');try{const tx=db.transaction(['products','inventory','inventoryTransactions','auditLogs'],'readwrite');let pid=id;if(id){await req('products','put',{...old,...obj,id},tx);const st={...(oldSt||{productId:id,quantity:0}),productId:id,quantity:qty,updatedAt:now()};await req('inventory','put',st,tx)}else{pid=await req('products','add',{...obj,createdAt:now()},tx);await req('inventory','put',{productId:pid,quantity:qty,updatedAt:now()},tx)}if(qty!==oldQty){const txType=id?'ADJUSTMENT':'OPENING';await req('inventoryTransactions','add',{productId:pid,type:txType,quantityChange:qty-oldQty,quantityBefore:oldQty,quantityAfter:qty,referenceId:null,note:note||(qty>0?'رصيد افتتاحي':'إنشاء الصنف'),createdAt:now()},tx)}await req('auditLogs','add',{action:id?'UPDATE_PRODUCT':'CREATE_PRODUCT',entityType:'product',entityId:pid,createdAt:now()},tx);await waitTx(tx);$('productDialog').close();await refresh();toast(id?'تم حفظ الصنف':'تم إضافة الصنف')}catch(e){console.error(e);alert('حدث خطأ في حفظ الصنف: '+(e.message||''))}});
function resetReceiveDialog(){ $('receiveProduct').innerHTML='<option value="">اختر الصنف</option>'+activeProducts().map(p=>`<option value="${p.id}">${esc(p.name)} — ${esc(p.code||'')}</option>`).join('');$('receiveQty').value='';$('receiveDate').value=new Date(new Date().getTime()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);$('receiveNote').value='';$('receiveDialog').showModal() }
function openReceiveStock(productId){resetReceiveDialog();$('receiveProduct').value=String(productId)}
$('receiveStockBtn').onclick=()=>resetReceiveDialog();
$('receiveForm').addEventListener('submit',async e=>{e.preventDefault();const pid=Number($('receiveProduct').value),qty=num($('receiveQty').value),dt=$('receiveDate').value?new Date($('receiveDate').value).toISOString():now(),note=$('receiveNote').value.trim();if(!pid)return alert('اختر الصنف');if(qty<=0)return alert('الكمية يجب أن تكون أكبر من صفر');if(!note)return alert('اكتب ملاحظة الاستلام حتى يسهل مراجعة الحركة لاحقًا.');const p=products.find(x=>x.id===pid),st=inventory.find(x=>x.productId===pid);if(!p||!st)return alert('الصنف غير موجود');const before=num(st.quantity),after=before+qty;try{const tx=db.transaction(['inventory','inventoryTransactions','auditLogs'],'readwrite');st.quantity=after;st.updatedAt=now();await req('inventory','put',st,tx);await req('inventoryTransactions','add',{productId:pid,type:'RECEIPT',quantityChange:qty,quantityBefore:before,quantityAfter:after,referenceId:null,note,createdAt:dt,recordedAt:now()},tx);await req('auditLogs','add',{action:'RECEIVE_STOCK',entityType:'product',entityId:pid,createdAt:now(),note},tx);await waitTx(tx);$('receiveDialog').close();await refresh();toast(`تم استلام ${money(qty)} ${p.unit} من ${p.name}`)}catch(e){console.error(e);alert('فشل حفظ استلام المخزون. لم يتم تحديث الرصيد.') }});
$('addLineBtn').onclick=addLine;$('confirmDispenseBtn').onclick=confirmDispense;$('clientSearch').oninput=renderClients;$('productSearch').oninput=renderProducts;$('invoiceSearch').oninput=renderInvoices;$('inventorySearch').oninput=renderInventory;$('movementSearch').oninput=renderInventoryLog;$('movementType').onchange=renderInventoryLog;$('movementFrom').onchange=renderInventoryLog;$('movementTo').onchange=renderInventoryLog;
document.querySelectorAll('#tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(b.dataset.screen).classList.add('active')});
async function loadInventoryTransactions(){inventoryTxCache=await all('inventoryTransactions');inventoryTxCache.sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||''))||(num(b.id)-num(a.id)))}
async function backup(){const data={version:3,exportedAt:now(),clients,products,inventory,invoices,invoiceItems:await all('invoiceItems'),inventoryTransactions:await all('inventoryTransactions'),auditLogs:await all('auditLogs'),settings:await all('settings')};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=`gamayati-backup-${monthKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500);toast('تم إنشاء النسخة الاحتياطية')}
async function restoreData(file){if(!file)throw Error('لم يتم اختيار ملف');const data=JSON.parse(await file.text());if(!data||Number(data.version||0)<1)throw Error('نسخة غير صالحة');if(!confirm('الاسترجاع سيستبدل البيانات الحالية. تأكد أن لديك نسخة احتياطية.'))return;const names=['clients','products','inventory','invoices','invoiceItems','inventoryTransactions','auditLogs','settings'];const tx=db.transaction(names,'readwrite');for(const n of names){const st=tx.objectStore(n);st.clear();for(const x of (data[n]||[]))st.put(x)}await waitTx(tx);await refresh();toast('تم استرجاع النسخة الاحتياطية.')}
$('backupBtn').onclick=backup;$('restoreBtn').onclick=()=>$('restoreFile').click();$('restoreFile').onchange=async e=>{try{await restoreData(e.target.files[0])}catch(err){alert('فشل الاسترجاع: '+err.message)}e.target.value=''};
$('saveSettingsBtn').onclick=async()=>{const v=Math.min(28,Math.max(1,Math.floor(num($('monthEndDay').value||25))));await put('settings',{key:'monthEndDay',value:v});settings.monthEndDay=v;renderDashboard();toast('تم حفظ الإعدادات')};
$('resetBtn').onclick=async()=>{if(!confirm('تحذير: سيتم حذف كل بيانات البرنامج من هذا الجهاز. هل أنت متأكد؟'))return;const names=['clients','products','inventory','invoices','invoiceItems','inventoryTransactions','auditLogs','settings'];const tx=db.transaction(names,'readwrite');names.forEach(n=>tx.objectStore(n).clear());await waitTx(tx);await refresh();toast('تم حذف البيانات')};
(async()=>{try{await openDB();await loadInventoryTransactions();await refresh()}catch(e){console.error(e);alert('تعذر فتح قاعدة بيانات جمعيتي: '+(e.message||''))}})();
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).catch(console.error);
